ftp_administrador:
    resource: "@FTPAdministradorBundle/Resources/config/routing.yml"
    prefix:   /administrador

ftp:
    path:     /
    defaults: { _controller: 'FTPAdministradorBundle:Default:login'}

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"